services:
  apr-framework:
    build:
      context: .
    working_dir: /workspace
    environment:
      BUGSINPY_HOME: /workspace/.tools/bugsinpy
      PYTHONPATH: /workspace/src
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true

#PROBLEM -> It takes too mich time to start the container
